import type { Metadata } from "next";
import RightSidebar from "@/components/right-sidebar";
import LeftSidebar from "@/components/left-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-slate-600 w-full min-h-screen grid md:grid-cols-3">
          <LeftSidebar />
          <div>{children}</div>
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
